routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('tasks','TaskController');
Auth::routes();

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    //table name
    protected $table='tasks';

    //primary key
    public $primaryKey='id';

    //timestamps
    public $timestamps = true;

    public function user(){
        return $this->belongsTo('App\User');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function tasks(){
        return $this->hasMany('App\Task');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Task;
use App\User;
use Illuminate\Http\Request;

class TaskController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user_id = auth()->user()->id;
        $tasks = Task::where('user_id',$user_id)->orderBy('created_at','desc')->get();

        return view('tasks.index')->with('tasks', $tasks);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tasks.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'taskName'        => 'required',
            'taskDescription' => 'required',
        ]);

        $task                   = new Task;
        $task->task_name        = $request->input('taskName');
        $task->task_description = $request->input('taskDescription');
        $task->user_id          = auth()->user()->id;
        $task->save();

        return redirect('/tasks')->with('success', 'task created');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Task $task
     *
     * @return \Illuminate\Http\Response
     */
    public function show(Task $task)
    {
        if (auth()->user()->id !== $task->user_id) {
            return redirect('/tasks')->with('error', 'Unauthorised page');
        }

        return view('tasks.show')->with('task', $task);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Task $task
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(Task $task)
    {
        //check for correct user
        if (auth()->user()->id !== $task->user_id) {
            return redirect('/tasks')->with('error', 'Unauthorised page');
        }

        return view('tasks.edit')->with('task', $task);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Task $task
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Task $task)
    {
        $this->validate($request, [
            'taskName'        => 'required',
            'taskDescription' => 'required',
        ]);

        $task->task_name        = $request->input('taskName');
        $task->task_description = $request->input('taskDescription');
        $task->completed = $request->input('completed')?true:false;
        $task->save();

        return redirect('/tasks')->with('success', 'task updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Task $task
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(Task $task)
    {
        //check for correct user
        if (auth()->user()->id !== $task->user_id) {
            return redirect('/tasks')->with('error', 'Unauthorised page');
        }

        $task->delete();

        return redirect('/tasks')->with('success', 'Task Removed');
    }
}

resources/views/inc/messages.blade.php
@if(count($errors)>0)
    @foreach($errors->all() as $error)
        <div class="container mt-4">
            <div class="alert alert-danger">
                {{$error}}
            </div>
        </div>
    @endforeach
@endif

@if(session('success'))
    <div class="container mt-4">
        <div class="alert alert-success">
            {{session('success')}}
        </div>
    </div>
@endif

@if(session('error'))
    <div class="container mt-4">
        <div class="alert alert-danger">
            {{session('error')}}
        </div>
    </div>
@endif

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="main">
            @include('inc.messages')

            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/tasks/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Create a Task</div>
                    <div class="card-body">
                        <form action="{{ route('tasks.store') }}" enctype="multipart/form-data" method="post">
                            @csrf

                            <div class="form-group">
                                <label for="taskName">Task name</label>
                                <input type="text" class="form-control" id="taskName" name="taskName">
                            </div>
                            <div class="form-group">
                                <label for="taskDescription">Task description</label>
                                <textarea class="form-control" id="taskDescription" rows="3"
                                          name="taskDescription"></textarea>
                            </div>
                            <button type="submit" class="btn btn-sm btn-primary">Create</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/tasks/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Create a Task</div>
                    <div class="card-body">
                        <form action="/tasks/{{$task->id}}" enctype="multipart/form-data" method="post">
                            @csrf
                            {{ method_field('PATCH') }}                            <div class="form-group">
                                <label for="taskName">Task name</label>
                                <input type="text" class="form-control" id="taskName" name="taskName"
                                       value="{{$task->task_name}}">
                            </div>
                            <div class="form-group">
                                <label for="taskDescription">Task description</label>
                                <textarea class="form-control" id="taskDescription" rows="3"
                                          name="taskDescription" >{{$task->task_description}}</textarea>
                            </div>
                            <button type="submit" class="btn btn-sm btn-primary">Update</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/tasks/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">To do tasks <a href="/tasks/create" class="float-right btn btn-sm
                    btn-success">Add task</a>
                    </div>

                    @if(count($tasks) > 0)
                        <ul class="list-group list-group-flush">
                            @foreach($tasks as $task)
                                @if(!$task->completed)
                                    <li class="list-group-item">
                                        <a href="/tasks/{{$task->id}}">{{$task->task_name}}</a>
                                        <form action="/tasks/{{$task->id}}" enctype="multipart/form-data" method="post"
                                              class="float-right">
                                            @csrf
                                            {{ method_field('PATCH') }}
                                            <input type="text" id="taskName" name="taskName"
                                                   value="{{$task->task_name}}" hidden>
                                            <input type="checkbox" id="completed" name="completed" checked hidden>
                                            <textarea id="taskDescription" rows="3"
                                                      name="taskDescription"
                                                      hidden>{{$task->task_description}}</textarea>
                                            <button type="submit" class="btn btn-sm btn-primary">Complete task</button>
                                        </form>
                                    </li>
                                @endif
                            @endforeach
                        </ul>
                    @else
                        <div class="card-body">
                            <p>No tasks found</p>
                        </div>
                    @endif


                </div>

                <div class="card mt-4">
                    <div class="card-header ">Completed tasks</div>
                    @if(count($tasks) > 0)
                        <ul class="list-group list-group-flush">
                            @foreach($tasks as $task)
                                @if($task->completed)
                                    <li class="list-group-item ">
                                        <a href="/tasks/{{$task->id}}">{{$task->task_name}}</a>
                                        <form action="/tasks/{{$task->id}}" enctype="multipart/form-data" method="post"
                                              class="float-right">
                                            @csrf
                                            {{ method_field('PATCH') }}
                                            <input type="text" id="taskName" name="taskName"
                                                   value="{{$task->task_name}}" hidden>
                                            <input type="checkbox" id="completed" name="completed" hidden>
                                            <textarea id="taskDescription" rows="3"
                                                      name="taskDescription"
                                                      hidden>{{$task->task_description}}</textarea>
                                            <button type="submit" class="btn btn-sm btn-secondary">Restore task</button>
                                        </form>
                                    </li>
                                @endif
                            @endforeach
                        </ul>
                    @else
                        <div class="card-body">
                            <p>No tasks found</p>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/tasks/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Create a Task</div>
                    <div class="card-body">
                        <h5 class="card-title">{{$task->task_name}}</h5>
                        <p class="card-text">{{$task->task_description}}</p>
                    </div>
                    <div class="card-footer">
                        <a href="/tasks/{{$task->id}}/edit" class="float-left btn btn-sm btn-primary">Edit</a>
                        <form action="/tasks/{{$task->id}}" method="post">
                            {{ method_field('DELETE') }}
                            @csrf
                            <button class="float-right btn btn-sm btn-danger" type="submit">Delete</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection